// Code generated by digen; DO NOT EDIT.

package rlhttp

import (
	"context"

	contextdi "github.com/Asmodai/gohacks/contextdi"
	errors "gitlab.com/tozd/go/errors"
)

// --- RLHTTP ---

// Key used to store the instance in the context's user value.
const ContextKeyRLHTTP = "gohacks/rlhttp@v1"

// Signalled if the instance associated with the context key is not of
// type *Client.
var ErrValueNotRLHTTP = errors.Base("value is not *Client")

// Set RLHTTP stores the instance in the context map.
func SetRLHTTP(ctx context.Context, inst *Client) (context.Context, error) {
	val, err := contextdi.PutToContext(ctx, ContextKeyRLHTTP, inst)
	if err != nil {
		return nil, errors.WithStack(err)
	}

	return val, nil
}

// Get the instance from the given context.
//
// Will return ErrValueNotRLHTTP if the value in the context is not of type
// *Client.
func GetRLHTTP(ctx context.Context) (*Client, error) {
	var zero *Client

	val, err := contextdi.GetFromContext(ctx, ContextKeyRLHTTP)
	if err != nil {
		return zero, errors.WithStack(err)
	}

	inst, ok := val.(*Client)
	if !ok {
		return zero, errors.WithStack(ErrValueNotRLHTTP)
	}

	return inst, nil
}

// Attempt to get the instance from the given context.  Panics if the
// operation fails.
func MustGetRLHTTP(ctx context.Context) *Client {
	inst, err := GetRLHTTP(ctx)

	if err != nil {
		panic(errors.WithMessage(err, "RLHTTP missing in context"))
	}

	return inst
}

// TryGetRLHTTP returns the instance and true if present and typed.
func TryGetRLHTTP(ctx context.Context) (*Client, bool) {
	var zero *Client

	val, err := contextdi.GetFromContext(ctx, ContextKeyRLHTTP)
	if err != nil {
		return zero, false
	}

	inst, ok := val.(*Client)
	if !ok {
		return zero, false
	}

	return inst, true
}

// FromRLHTTP returns the instance or the fallback.
func FromRLHTTP(ctx context.Context) *Client {
	if v, ok := TryGetRLHTTP(ctx); ok {
		return v
	}

	return NewDefault()
}

// WithRLHTTP calls fn with the instance or fallback.
func WithRLHTTP(ctx context.Context, fn func(*Client)) {
	fn(FromRLHTTP(ctx))
}

// SetRLHTTPIfAbsent sets only if not already present.
func SetRLHTTPIfAbsent(ctx context.Context, inst *Client) (context.Context, error) {
	if _, ok := TryGetRLHTTP(ctx); ok {
		return ctx, nil
	}

	return SetRLHTTP(ctx, inst)
}
