// Code generated by MockGen. DO NOT EDIT.
// Source: ./apiclient/client.go
//
// Generated by this command:
//
//	mockgen -package=apiclient -source=./apiclient/client.go -destination=mocks/apiclient/client_mock.go
//

// Package apiclient is a generated GoMock package.
package apiclient

import (
	context "context"
	reflect "reflect"

	apiclient "github.com/Asmodai/gohacks/apiclient"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockClient) Get(arg0 *apiclient.Params) apiclient.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(apiclient.Response)
	return ret0
}

// Get indicates an expected call of Get.
func (mr *MockClientMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockClient)(nil).Get), arg0)
}

// GetWithContext mocks base method.
func (m *MockClient) GetWithContext(arg0 context.Context, arg1 *apiclient.Params) apiclient.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithContext", arg0, arg1)
	ret0, _ := ret[0].(apiclient.Response)
	return ret0
}

// GetWithContext indicates an expected call of GetWithContext.
func (mr *MockClientMockRecorder) GetWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithContext", reflect.TypeOf((*MockClient)(nil).GetWithContext), arg0, arg1)
}

// Post mocks base method.
func (m *MockClient) Post(arg0 *apiclient.Params) apiclient.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Post", arg0)
	ret0, _ := ret[0].(apiclient.Response)
	return ret0
}

// Post indicates an expected call of Post.
func (mr *MockClientMockRecorder) Post(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Post", reflect.TypeOf((*MockClient)(nil).Post), arg0)
}

// PostWithContext mocks base method.
func (m *MockClient) PostWithContext(arg0 context.Context, arg1 *apiclient.Params) apiclient.Response {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PostWithContext", arg0, arg1)
	ret0, _ := ret[0].(apiclient.Response)
	return ret0
}

// PostWithContext indicates an expected call of PostWithContext.
func (mr *MockClientMockRecorder) PostWithContext(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PostWithContext", reflect.TypeOf((*MockClient)(nil).PostWithContext), arg0, arg1)
}
