// Code generated by MockGen. DO NOT EDIT.
// Source: ./scheduler/timed_job.go
//
// Generated by this command:
//
//	mockgen -package=scheduler -source=./scheduler/timed_job.go -destination=mocks/scheduler/timed_job_mock.go
//

// Package scheduler is a generated GoMock package.
package scheduler

import (
	context "context"
	reflect "reflect"
	time "time"

	scheduler "github.com/Asmodai/gohacks/scheduler"
	gomock "go.uber.org/mock/gomock"
)

// MockTimedJob is a mock of TimedJob interface.
type MockTimedJob struct {
	ctrl     *gomock.Controller
	recorder *MockTimedJobMockRecorder
	isgomock struct{}
}

// MockTimedJobMockRecorder is the mock recorder for MockTimedJob.
type MockTimedJobMockRecorder struct {
	mock *MockTimedJob
}

// NewMockTimedJob creates a new mock instance.
func NewMockTimedJob(ctrl *gomock.Controller) *MockTimedJob {
	mock := &MockTimedJob{ctrl: ctrl}
	mock.recorder = &MockTimedJobMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimedJob) EXPECT() *MockTimedJobMockRecorder {
	return m.recorder
}

// Function mocks base method.
func (m *MockTimedJob) Function() scheduler.JobFn {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Function")
	ret0, _ := ret[0].(scheduler.JobFn)
	return ret0
}

// Function indicates an expected call of Function.
func (mr *MockTimedJobMockRecorder) Function() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Function", reflect.TypeOf((*MockTimedJob)(nil).Function))
}

// Object mocks base method.
func (m *MockTimedJob) Object() scheduler.Task {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Object")
	ret0, _ := ret[0].(scheduler.Task)
	return ret0
}

// Object indicates an expected call of Object.
func (mr *MockTimedJobMockRecorder) Object() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Object", reflect.TypeOf((*MockTimedJob)(nil).Object))
}

// Resolve mocks base method.
func (m *MockTimedJob) Resolve(arg0 context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Resolve", arg0)
	ret0, _ := ret[0].(error)
	return ret0
}

// Resolve indicates an expected call of Resolve.
func (mr *MockTimedJobMockRecorder) Resolve(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Resolve", reflect.TypeOf((*MockTimedJob)(nil).Resolve), arg0)
}

// RunAt mocks base method.
func (m *MockTimedJob) RunAt() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RunAt")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// RunAt indicates an expected call of RunAt.
func (mr *MockTimedJobMockRecorder) RunAt() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RunAt", reflect.TypeOf((*MockTimedJob)(nil).RunAt))
}

// Validate mocks base method.
func (m *MockTimedJob) Validate() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate")
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockTimedJobMockRecorder) Validate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockTimedJob)(nil).Validate))
}
