run:
  concurrency: 4
  timeout: 5m
  issues-exit-code: 2
  tests: false
  build-tags:
    - testing
  modules-download-mode: readonly
  allow-parallel-runners: true
  allow-serial-runners: true
  go: '1.23.5'
  
output:
  formats:
    - format: json
      path: stderr
    - format: checkstyle
      path: report.xml
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
  path-prefix: ""
  sort-results: true
  sort-order:
    - linter
    - severity
    - file
  show-stats: true

issues:
  uniq-by-line: false
  exclude-rules:
    - linters:
      - godot
      text: '^// \*+ \w+:$'

linger-settings:
  godox:
    keywords:
      - OPTIMIZE
      - HACK
      - FIXME
      - BUG
  gofmt:
    simplify: false
    rewrite-rules:
      - pattern:     'interface{}'
        replacement: 'any'
      - pattern:     'a[b:len(a)]'
        replacement: 'a[b:]'

linters:
  enable-all: true
  disable:
    - depguard
    - exhaustruct
    # This one should be re-enabled at some point
    #- goerr113
    - tagliatelle
    - gofumpt
    - gci
    - ireturn
    - interfacebloat
    - inamedparam
    - goimports
    #- gofmt
    - godox
    - containedctx
    #
    # Deprecated linters
    - tenv
