// Code generated by digen; DO NOT EDIT.

package cache

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- Cache ---

func TestCacheDI(t *testing.T) {
	t.Run("SetCache", func(t *testing.T) {
		inst := NewDefault()
		_, err := SetCache(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetCache", func(t *testing.T) {
		inst := NewDefault()
		ctx, err := SetCache(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetCache(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetCache", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "Cache missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errx.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetCache(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetCache(context.Background(), NewDefault())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetCache(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetCache", func(t *testing.T) {
		var zero Cache

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetCache(context.Background(), NewDefault())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetCache(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetCache(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromCache", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefault())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefault()

			ctx, err := SetCache(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromCache(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromCache(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithCache", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefault())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefault()

			ctx, err := SetCache(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithCache(ctx, func(obj Cache) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithCache(context.Background(), func(obj Cache) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
