// Code generated by digen; DO NOT EDIT.

package cache

import (
	"context"

	contextdi "github.com/Asmodai/gohacks/contextdi"
	errx "github.com/Asmodai/gohacks/errx"
)

// --- Cache ---

// Key used to store the instance in the context's user value.
const ContextKeyCache = "gohacks/cache@v1"

// Signalled if the instance associated with the context key is not of
// type Cache.
var ErrValueNotCache = errx.Base("value is not Cache")

// Set Cache stores the instance in the context map.
func SetCache(ctx context.Context, inst Cache) (context.Context, error) {
	val, err := contextdi.PutToContext(ctx, ContextKeyCache, inst)
	if err != nil {
		return nil, errx.WithStack(err)
	}

	return val, nil
}

// Get the instance from the given context.
//
// Will return ErrValueNotCache if the value in the context is not of type
// Cache.
func GetCache(ctx context.Context) (Cache, error) {
	var zero Cache

	val, err := contextdi.GetFromContext(ctx, ContextKeyCache)
	if err != nil {
		return zero, errx.WithStack(err)
	}

	inst, ok := val.(Cache)
	if !ok {
		return zero, errx.WithStack(ErrValueNotCache)
	}

	return inst, nil
}

// Attempt to get the instance from the given context.  Panics if the
// operation fails.
func MustGetCache(ctx context.Context) Cache {
	inst, err := GetCache(ctx)

	if err != nil {
		panic(errx.WithMessage(err, "Cache missing in context"))
	}

	return inst
}

// TryGetCache returns the instance and true if present and typed.
func TryGetCache(ctx context.Context) (Cache, bool) {
	var zero Cache

	val, err := contextdi.GetFromContext(ctx, ContextKeyCache)
	if err != nil {
		return zero, false
	}

	inst, ok := val.(Cache)
	if !ok {
		return zero, false
	}

	return inst, true
}

// FromCache returns the instance or the fallback.
func FromCache(ctx context.Context) Cache {
	if v, ok := TryGetCache(ctx); ok {
		return v
	}

	return NewDefault()
}

// WithCache calls fn with the instance or fallback.
func WithCache(ctx context.Context, fn func(Cache)) {
	fn(FromCache(ctx))
}

// SetCacheIfAbsent sets only if not already present.
func SetCacheIfAbsent(ctx context.Context, inst Cache) (context.Context, error) {
	if _, ok := TryGetCache(ctx); ok {
		return ctx, nil
	}

	return SetCache(ctx, inst)
}
