// Code generated by MockGen. DO NOT EDIT.
// Source: ./expertsys/types.go
//
// Generated by this command:
//
//	mockgen -package=expertsys -source=./expertsys/types.go -destination=mocks/expertsys/types_mock.go
//

// Package expertsys is a generated GoMock package.
package expertsys

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockWorkingMemory is a mock of WorkingMemory interface.
type MockWorkingMemory struct {
	ctrl     *gomock.Controller
	recorder *MockWorkingMemoryMockRecorder
	isgomock struct{}
}

// MockWorkingMemoryMockRecorder is the mock recorder for MockWorkingMemory.
type MockWorkingMemoryMockRecorder struct {
	mock *MockWorkingMemory
}

// NewMockWorkingMemory creates a new mock instance.
func NewMockWorkingMemory(ctrl *gomock.Controller) *MockWorkingMemory {
	mock := &MockWorkingMemory{ctrl: ctrl}
	mock.recorder = &MockWorkingMemoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWorkingMemory) EXPECT() *MockWorkingMemoryMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockWorkingMemory) Get(arg0 string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockWorkingMemoryMockRecorder) Get(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockWorkingMemory)(nil).Get), arg0)
}

// Keys mocks base method.
func (m *MockWorkingMemory) Keys() []string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Keys")
	ret0, _ := ret[0].([]string)
	return ret0
}

// Keys indicates an expected call of Keys.
func (mr *MockWorkingMemoryMockRecorder) Keys() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Keys", reflect.TypeOf((*MockWorkingMemory)(nil).Keys))
}

// Set mocks base method.
func (m *MockWorkingMemory) Set(arg0 string, arg1 any) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", arg0, arg1)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockWorkingMemoryMockRecorder) Set(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockWorkingMemory)(nil).Set), arg0, arg1)
}

// String mocks base method.
func (m *MockWorkingMemory) String() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "String")
	ret0, _ := ret[0].(string)
	return ret0
}

// String indicates an expected call of String.
func (mr *MockWorkingMemoryMockRecorder) String() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "String", reflect.TypeOf((*MockWorkingMemory)(nil).String))
}

// Version mocks base method.
func (m *MockWorkingMemory) Version() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockWorkingMemoryMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockWorkingMemory)(nil).Version))
}
