// Code generated by MockGen. DO NOT EDIT.
// Source: ./selector/respondable.go
//
// Generated by this command:
//
//	mockgen -package=selector -source=./selector/respondable.go -destination=mocks/selector/respondable_mock.go
//

// Package selector is a generated GoMock package.
package selector
