// Code generated by MockGen. DO NOT EDIT.
// Source: ./health/interface.go
//
// Generated by this command:
//
//	mockgen -package=health -source=./health/interface.go -destination=mocks/health/interface_mock.go
//

// Package health is a generated GoMock package.
package health

import (
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockReporter is a mock of Reporter interface.
type MockReporter struct {
	ctrl     *gomock.Controller
	recorder *MockReporterMockRecorder
	isgomock struct{}
}

// MockReporterMockRecorder is the mock recorder for MockReporter.
type MockReporterMockRecorder struct {
	mock *MockReporter
}

// NewMockReporter creates a new mock instance.
func NewMockReporter(ctrl *gomock.Controller) *MockReporter {
	mock := &MockReporter{ctrl: ctrl}
	mock.recorder = &MockReporterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReporter) EXPECT() *MockReporterMockRecorder {
	return m.recorder
}

// Healthy mocks base method.
func (m *MockReporter) Healthy() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Healthy")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Healthy indicates an expected call of Healthy.
func (mr *MockReporterMockRecorder) Healthy() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Healthy", reflect.TypeOf((*MockReporter)(nil).Healthy))
}

// LastHeartbeat mocks base method.
func (m *MockReporter) LastHeartbeat() time.Time {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastHeartbeat")
	ret0, _ := ret[0].(time.Time)
	return ret0
}

// LastHeartbeat indicates an expected call of LastHeartbeat.
func (mr *MockReporterMockRecorder) LastHeartbeat() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastHeartbeat", reflect.TypeOf((*MockReporter)(nil).LastHeartbeat))
}

// Tick mocks base method.
func (m *MockReporter) Tick() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Tick")
}

// Tick indicates an expected call of Tick.
func (mr *MockReporterMockRecorder) Tick() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tick", reflect.TypeOf((*MockReporter)(nil).Tick))
}

// UserGet mocks base method.
func (m *MockReporter) UserGet(arg0 string) (any, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserGet", arg0)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// UserGet indicates an expected call of UserGet.
func (mr *MockReporterMockRecorder) UserGet(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserGet", reflect.TypeOf((*MockReporter)(nil).UserGet), arg0)
}

// UserSet mocks base method.
func (m *MockReporter) UserSet(arg0 string, arg1 any) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UserSet", arg0, arg1)
}

// UserSet indicates an expected call of UserSet.
func (mr *MockReporterMockRecorder) UserSet(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserSet", reflect.TypeOf((*MockReporter)(nil).UserSet), arg0, arg1)
}
