// Code generated by MockGen. DO NOT EDIT.
// Source: ./app/app.go
//
// Generated by this command:
//
//	mockgen -package=app -source=./app/app.go -destination=mocks/app/app_mock.go
//

// Package app is a generated GoMock package.
package app

import (
	context "context"
	reflect "reflect"

	app "github.com/Asmodai/gohacks/app"
	config "github.com/Asmodai/gohacks/config"
	events "github.com/Asmodai/gohacks/events"
	logger "github.com/Asmodai/gohacks/logger"
	process "github.com/Asmodai/gohacks/process"
	responder "github.com/Asmodai/gohacks/responder"
	semver "github.com/Asmodai/gohacks/semver"
	gomock "go.uber.org/mock/gomock"
)

// MockApplication is a mock of Application interface.
type MockApplication struct {
	ctrl     *gomock.Controller
	recorder *MockApplicationMockRecorder
	isgomock struct{}
}

// MockApplicationMockRecorder is the mock recorder for MockApplication.
type MockApplicationMockRecorder struct {
	mock *MockApplication
}

// NewMockApplication creates a new mock instance.
func NewMockApplication(ctrl *gomock.Controller) *MockApplication {
	mock := &MockApplication{ctrl: ctrl}
	mock.recorder = &MockApplicationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockApplication) EXPECT() *MockApplicationMockRecorder {
	return m.recorder
}

// AddResponder mocks base method.
func (m *MockApplication) AddResponder(arg0 responder.Respondable) (responder.Respondable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddResponder", arg0)
	ret0, _ := ret[0].(responder.Respondable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddResponder indicates an expected call of AddResponder.
func (mr *MockApplicationMockRecorder) AddResponder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddResponder", reflect.TypeOf((*MockApplication)(nil).AddResponder), arg0)
}

// Commit mocks base method.
func (m *MockApplication) Commit() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit")
	ret0, _ := ret[0].(string)
	return ret0
}

// Commit indicates an expected call of Commit.
func (mr *MockApplicationMockRecorder) Commit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockApplication)(nil).Commit))
}

// Configuration mocks base method.
func (m *MockApplication) Configuration() config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Configuration")
	ret0, _ := ret[0].(config.Config)
	return ret0
}

// Configuration indicates an expected call of Configuration.
func (mr *MockApplicationMockRecorder) Configuration() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Configuration", reflect.TypeOf((*MockApplication)(nil).Configuration))
}

// Context mocks base method.
func (m *MockApplication) Context() context.Context {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Context")
	ret0, _ := ret[0].(context.Context)
	return ret0
}

// Context indicates an expected call of Context.
func (mr *MockApplicationMockRecorder) Context() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Context", reflect.TypeOf((*MockApplication)(nil).Context))
}

// Init mocks base method.
func (m *MockApplication) Init() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Init")
}

// Init indicates an expected call of Init.
func (mr *MockApplicationMockRecorder) Init() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Init", reflect.TypeOf((*MockApplication)(nil).Init))
}

// Invoke mocks base method.
func (m *MockApplication) Invoke(arg0 events.Event) events.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Invoke", arg0)
	ret0, _ := ret[0].(events.Event)
	return ret0
}

// Invoke indicates an expected call of Invoke.
func (mr *MockApplicationMockRecorder) Invoke(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Invoke", reflect.TypeOf((*MockApplication)(nil).Invoke), arg0)
}

// IsDebug mocks base method.
func (m *MockApplication) IsDebug() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsDebug")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsDebug indicates an expected call of IsDebug.
func (mr *MockApplicationMockRecorder) IsDebug() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsDebug", reflect.TypeOf((*MockApplication)(nil).IsDebug))
}

// IsRunning mocks base method.
func (m *MockApplication) IsRunning() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsRunning")
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsRunning indicates an expected call of IsRunning.
func (mr *MockApplicationMockRecorder) IsRunning() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsRunning", reflect.TypeOf((*MockApplication)(nil).IsRunning))
}

// Logger mocks base method.
func (m *MockApplication) Logger() logger.Logger {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logger")
	ret0, _ := ret[0].(logger.Logger)
	return ret0
}

// Logger indicates an expected call of Logger.
func (mr *MockApplicationMockRecorder) Logger() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logger", reflect.TypeOf((*MockApplication)(nil).Logger))
}

// Name mocks base method.
func (m *MockApplication) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockApplicationMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockApplication)(nil).Name))
}

// ParseConfig mocks base method.
func (m *MockApplication) ParseConfig() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ParseConfig")
}

// ParseConfig indicates an expected call of ParseConfig.
func (mr *MockApplicationMockRecorder) ParseConfig() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseConfig", reflect.TypeOf((*MockApplication)(nil).ParseConfig))
}

// ProcessManager mocks base method.
func (m *MockApplication) ProcessManager() process.Manager {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessManager")
	ret0, _ := ret[0].(process.Manager)
	return ret0
}

// ProcessManager indicates an expected call of ProcessManager.
func (mr *MockApplicationMockRecorder) ProcessManager() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessManager", reflect.TypeOf((*MockApplication)(nil).ProcessManager))
}

// RemoveResponder mocks base method.
func (m *MockApplication) RemoveResponder(arg0 responder.Respondable) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveResponder", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RemoveResponder indicates an expected call of RemoveResponder.
func (mr *MockApplicationMockRecorder) RemoveResponder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveResponder", reflect.TypeOf((*MockApplication)(nil).RemoveResponder), arg0)
}

// RespondsTo mocks base method.
func (m *MockApplication) RespondsTo(arg0 events.Event) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RespondsTo", arg0)
	ret0, _ := ret[0].(bool)
	return ret0
}

// RespondsTo indicates an expected call of RespondsTo.
func (mr *MockApplicationMockRecorder) RespondsTo(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RespondsTo", reflect.TypeOf((*MockApplication)(nil).RespondsTo), arg0)
}

// Run mocks base method.
func (m *MockApplication) Run() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run")
}

// Run indicates an expected call of Run.
func (mr *MockApplicationMockRecorder) Run() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockApplication)(nil).Run))
}

// SendAllResponders mocks base method.
func (m *MockApplication) SendAllResponders(arg0 events.Event) []events.Event {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendAllResponders", arg0)
	ret0, _ := ret[0].([]events.Event)
	return ret0
}

// SendAllResponders indicates an expected call of SendAllResponders.
func (mr *MockApplicationMockRecorder) SendAllResponders(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendAllResponders", reflect.TypeOf((*MockApplication)(nil).SendAllResponders), arg0)
}

// SendFirstResponder mocks base method.
func (m *MockApplication) SendFirstResponder(arg0 events.Event) (events.Event, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendFirstResponder", arg0)
	ret0, _ := ret[0].(events.Event)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// SendFirstResponder indicates an expected call of SendFirstResponder.
func (mr *MockApplicationMockRecorder) SendFirstResponder(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendFirstResponder", reflect.TypeOf((*MockApplication)(nil).SendFirstResponder), arg0)
}

// SetContext mocks base method.
func (m *MockApplication) SetContext(arg0 context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetContext", arg0)
}

// SetContext indicates an expected call of SetContext.
func (mr *MockApplicationMockRecorder) SetContext(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetContext", reflect.TypeOf((*MockApplication)(nil).SetContext), arg0)
}

// SetMainLoop mocks base method.
func (m *MockApplication) SetMainLoop(arg0 app.MainLoopFn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetMainLoop", arg0)
}

// SetMainLoop indicates an expected call of SetMainLoop.
func (mr *MockApplicationMockRecorder) SetMainLoop(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetMainLoop", reflect.TypeOf((*MockApplication)(nil).SetMainLoop), arg0)
}

// SetOnExit mocks base method.
func (m *MockApplication) SetOnExit(arg0 app.CallbackFn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnExit", arg0)
}

// SetOnExit indicates an expected call of SetOnExit.
func (mr *MockApplicationMockRecorder) SetOnExit(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnExit", reflect.TypeOf((*MockApplication)(nil).SetOnExit), arg0)
}

// SetOnStart mocks base method.
func (m *MockApplication) SetOnStart(arg0 app.CallbackFn) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetOnStart", arg0)
}

// SetOnStart indicates an expected call of SetOnStart.
func (mr *MockApplicationMockRecorder) SetOnStart(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOnStart", reflect.TypeOf((*MockApplication)(nil).SetOnStart), arg0)
}

// Terminate mocks base method.
func (m *MockApplication) Terminate() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Terminate")
}

// Terminate indicates an expected call of Terminate.
func (mr *MockApplicationMockRecorder) Terminate() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Terminate", reflect.TypeOf((*MockApplication)(nil).Terminate))
}

// Type mocks base method.
func (m *MockApplication) Type() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Type")
	ret0, _ := ret[0].(string)
	return ret0
}

// Type indicates an expected call of Type.
func (mr *MockApplicationMockRecorder) Type() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Type", reflect.TypeOf((*MockApplication)(nil).Type))
}

// Version mocks base method.
func (m *MockApplication) Version() *semver.SemVer {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(*semver.SemVer)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockApplicationMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockApplication)(nil).Version))
}
