// Code generated by digen; DO NOT EDIT.

package health

import (
	"context"

	contextdi "github.com/Asmodai/gohacks/contextdi"
	errors "gitlab.com/tozd/go/errors"
)

// --- Health ---

// Key used to store the instance in the context's user value.
const ContextKeyHealth = "gohacks/health@v1"

// Signalled if the instance associated with the context key is not of
// type Reporter.
var ErrValueNotHealth = errors.Base("value is not Reporter")

// Set Health stores the instance in the context map.
func SetHealth(ctx context.Context, inst Reporter) (context.Context, error) {
	val, err := contextdi.PutToContext(ctx, ContextKeyHealth, inst)
	if err != nil {
		return nil, errors.WithStack(err)
	}

	return val, nil
}

// Get the instance from the given context.
//
// Will return ErrValueNotHealth if the value in the context is not of type
// Reporter.
func GetHealth(ctx context.Context) (Reporter, error) {
	var zero Reporter

	val, err := contextdi.GetFromContext(ctx, ContextKeyHealth)
	if err != nil {
		return zero, errors.WithStack(err)
	}

	inst, ok := val.(Reporter)
	if !ok {
		return zero, errors.WithStack(ErrValueNotHealth)
	}

	return inst, nil
}

// Attempt to get the instance from the given context.  Panics if the
// operation fails.
func MustGetHealth(ctx context.Context) Reporter {
	inst, err := GetHealth(ctx)

	if err != nil {
		panic(errors.WithMessage(err, "Health missing in context"))
	}

	return inst
}

// TryGetHealth returns the instance and true if present and typed.
func TryGetHealth(ctx context.Context) (Reporter, bool) {
	var zero Reporter

	val, err := contextdi.GetFromContext(ctx, ContextKeyHealth)
	if err != nil {
		return zero, false
	}

	inst, ok := val.(Reporter)
	if !ok {
		return zero, false
	}

	return inst, true
}

// FromHealth returns the instance or the fallback.
func FromHealth(ctx context.Context) Reporter {
	if v, ok := TryGetHealth(ctx); ok {
		return v
	}

	return NewDefaultHealth()
}

// WithHealth calls fn with the instance or fallback.
func WithHealth(ctx context.Context, fn func(Reporter)) {
	fn(FromHealth(ctx))
}

// SetHealthIfAbsent sets only if not already present.
func SetHealthIfAbsent(ctx context.Context, inst Reporter) (context.Context, error) {
	if _, ok := TryGetHealth(ctx); ok {
		return ctx, nil
	}

	return SetHealth(ctx, inst)
}
