// Code generated by digen; DO NOT EDIT.

package health

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- Health ---

func TestHealthDI(t *testing.T) {
	t.Run("SetHealth", func(t *testing.T) {
		inst := NewDefaultHealth()
		_, err := SetHealth(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetHealth", func(t *testing.T) {
		inst := NewDefaultHealth()
		ctx, err := SetHealth(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetHealth(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetHealth", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "Health missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errors.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetHealth(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetHealth(context.Background(), NewDefaultHealth())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetHealth(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetHealth", func(t *testing.T) {
		var zero Reporter

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetHealth(context.Background(), NewDefaultHealth())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetHealth(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetHealth(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromHealth", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultHealth())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultHealth()

			ctx, err := SetHealth(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromHealth(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromHealth(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithHealth", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultHealth())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultHealth()

			ctx, err := SetHealth(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithHealth(ctx, func(obj Reporter) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithHealth(context.Background(), func(obj Reporter) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
