// Code generated by digen; DO NOT EDIT.

package apiclient

import (
	"context"

	contextdi "github.com/Asmodai/gohacks/contextdi"
	errx "github.com/Asmodai/gohacks/errx"
)

// --- Client ---

// Key used to store the instance in the context's user value.
const ContextKeyClient = "gohacks/apiclient/Client@v1"

// Signalled if the instance associated with the context key is not of
// type Client.
var ErrValueNotClient = errx.Base("value is not Client")

// Set Client stores the instance in the context map.
func SetClient(ctx context.Context, inst Client) (context.Context, error) {
	val, err := contextdi.PutToContext(ctx, ContextKeyClient, inst)
	if err != nil {
		return nil, errx.WithStack(err)
	}

	return val, nil
}

// Get the instance from the given context.
//
// Will return ErrValueNotClient if the value in the context is not of type
// Client.
func GetClient(ctx context.Context) (Client, error) {
	var zero Client

	val, err := contextdi.GetFromContext(ctx, ContextKeyClient)
	if err != nil {
		return zero, errx.WithStack(err)
	}

	inst, ok := val.(Client)
	if !ok {
		return zero, errx.WithStack(ErrValueNotClient)
	}

	return inst, nil
}

// Attempt to get the instance from the given context.  Panics if the
// operation fails.
func MustGetClient(ctx context.Context) Client {
	inst, err := GetClient(ctx)

	if err != nil {
		panic(errx.WithMessage(err, "Client missing in context"))
	}

	return inst
}

// TryGetClient returns the instance and true if present and typed.
func TryGetClient(ctx context.Context) (Client, bool) {
	var zero Client

	val, err := contextdi.GetFromContext(ctx, ContextKeyClient)
	if err != nil {
		return zero, false
	}

	inst, ok := val.(Client)
	if !ok {
		return zero, false
	}

	return inst, true
}

// FromClient returns the instance or the fallback.
func FromClient(ctx context.Context) Client {
	if v, ok := TryGetClient(ctx); ok {
		return v
	}

	return NewDefaultClient()
}

// WithClient calls fn with the instance or fallback.
func WithClient(ctx context.Context, fn func(Client)) {
	fn(FromClient(ctx))
}

// SetClientIfAbsent sets only if not already present.
func SetClientIfAbsent(ctx context.Context, inst Client) (context.Context, error) {
	if _, ok := TryGetClient(ctx); ok {
		return ctx, nil
	}

	return SetClient(ctx, inst)
}
