// Code generated by digen; DO NOT EDIT.

package apiclient

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- HTTPClient ---

func TestHTTPClientDI(t *testing.T) {
	t.Run("SetHTTPClient", func(t *testing.T) {
		inst := NewDefaultHTTPClient()
		_, err := SetHTTPClient(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetHTTPClient", func(t *testing.T) {
		inst := NewDefaultHTTPClient()
		ctx, err := SetHTTPClient(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetHTTPClient(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetHTTPClient", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "HTTPClient missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errors.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetHTTPClient(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetHTTPClient(context.Background(), NewDefaultHTTPClient())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetHTTPClient(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetHTTPClient", func(t *testing.T) {
		var zero HTTPClient

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetHTTPClient(context.Background(), NewDefaultHTTPClient())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetHTTPClient(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetHTTPClient(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromHTTPClient", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultHTTPClient())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultHTTPClient()

			ctx, err := SetHTTPClient(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromHTTPClient(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromHTTPClient(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithHTTPClient", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultHTTPClient())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultHTTPClient()

			ctx, err := SetHTTPClient(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithHTTPClient(ctx, func(obj HTTPClient) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithHTTPClient(context.Background(), func(obj HTTPClient) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
