// Code generated by digen; DO NOT EDIT.

package apiclient

import (
	"context"

	contextdi "github.com/Asmodai/gohacks/contextdi"
	errors "gitlab.com/tozd/go/errors"
)

// --- HTTPClient ---

// Key used to store the instance in the context's user value.
const ContextKeyHTTPClient = "/gohacks/apiclient/HTTPClient@v1"

// Signalled if the instance associated with the context key is not of
// type HTTPClient.
var ErrValueNotHTTPClient = errors.Base("value is not HTTPClient")

// Set HTTPClient stores the instance in the context map.
func SetHTTPClient(ctx context.Context, inst HTTPClient) (context.Context, error) {
	val, err := contextdi.PutToContext(ctx, ContextKeyHTTPClient, inst)
	if err != nil {
		return nil, errors.WithStack(err)
	}

	return val, nil
}

// Get the instance from the given context.
//
// Will return ErrValueNotHTTPClient if the value in the context is not of type
// HTTPClient.
func GetHTTPClient(ctx context.Context) (HTTPClient, error) {
	var zero HTTPClient

	val, err := contextdi.GetFromContext(ctx, ContextKeyHTTPClient)
	if err != nil {
		return zero, errors.WithStack(err)
	}

	inst, ok := val.(HTTPClient)
	if !ok {
		return zero, errors.WithStack(ErrValueNotHTTPClient)
	}

	return inst, nil
}

// Attempt to get the instance from the given context.  Panics if the
// operation fails.
func MustGetHTTPClient(ctx context.Context) HTTPClient {
	inst, err := GetHTTPClient(ctx)

	if err != nil {
		panic(errors.WithMessage(err, "HTTPClient missing in context"))
	}

	return inst
}

// TryGetHTTPClient returns the instance and true if present and typed.
func TryGetHTTPClient(ctx context.Context) (HTTPClient, bool) {
	var zero HTTPClient

	val, err := contextdi.GetFromContext(ctx, ContextKeyHTTPClient)
	if err != nil {
		return zero, false
	}

	inst, ok := val.(HTTPClient)
	if !ok {
		return zero, false
	}

	return inst, true
}

// FromHTTPClient returns the instance or the fallback.
func FromHTTPClient(ctx context.Context) HTTPClient {
	if v, ok := TryGetHTTPClient(ctx); ok {
		return v
	}

	return NewDefaultHTTPClient()
}

// WithHTTPClient calls fn with the instance or fallback.
func WithHTTPClient(ctx context.Context, fn func(HTTPClient)) {
	fn(FromHTTPClient(ctx))
}

// SetHTTPClientIfAbsent sets only if not already present.
func SetHTTPClientIfAbsent(ctx context.Context, inst HTTPClient) (context.Context, error) {
	if _, ok := TryGetHTTPClient(ctx); ok {
		return ctx, nil
	}

	return SetHTTPClient(ctx, inst)
}
