// Code generated by digen; DO NOT EDIT.

package memoise

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- Memoise ---

func TestMemoiseDI(t *testing.T) {
	t.Run("SetMemoise", func(t *testing.T) {
		inst := NewDefaultMemoise()
		_, err := SetMemoise(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetMemoise", func(t *testing.T) {
		inst := NewDefaultMemoise()
		ctx, err := SetMemoise(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetMemoise(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetMemoise", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "Memoise missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errx.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetMemoise(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetMemoise(context.Background(), NewDefaultMemoise())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetMemoise(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetMemoise", func(t *testing.T) {
		var zero Memoise

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetMemoise(context.Background(), NewDefaultMemoise())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetMemoise(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetMemoise(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromMemoise", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultMemoise())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultMemoise()

			ctx, err := SetMemoise(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromMemoise(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromMemoise(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithMemoise", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefaultMemoise())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefaultMemoise()

			ctx, err := SetMemoise(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithMemoise(ctx, func(obj Memoise) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithMemoise(context.Background(), func(obj Memoise) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
