// Code generated by MockGen. DO NOT EDIT.
// Source: ./lucette/nnf.go
//
// Generated by this command:
//
//	mockgen -package=lucette -source=./lucette/nnf.go -destination=mocks/lucette/nnf_mock.go
//

// Package lucette is a generated GoMock package.
package lucette

import (
	reflect "reflect"

	lucette "github.com/Asmodai/gohacks/lucette"
	gomock "go.uber.org/mock/gomock"
)

// MockNNF is a mock of NNF interface.
type MockNNF struct {
	ctrl     *gomock.Controller
	recorder *MockNNFMockRecorder
	isgomock struct{}
}

// MockNNFMockRecorder is the mock recorder for MockNNF.
type MockNNFMockRecorder struct {
	mock *MockNNF
}

// NewMockNNF creates a new mock instance.
func NewMockNNF(ctrl *gomock.Controller) *MockNNF {
	mock := &MockNNF{ctrl: ctrl}
	mock.recorder = &MockNNFMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNNF) EXPECT() *MockNNFMockRecorder {
	return m.recorder
}

// NNF mocks base method.
func (m *MockNNF) NNF(arg0 lucette.IRNode) lucette.IRNode {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NNF", arg0)
	ret0, _ := ret[0].(lucette.IRNode)
	return ret0
}

// NNF indicates an expected call of NNF.
func (mr *MockNNFMockRecorder) NNF(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NNF", reflect.TypeOf((*MockNNF)(nil).NNF), arg0)
}
