// Code generated by digen; DO NOT EDIT.

package process

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- Manager ---

func TestManagerDI(t *testing.T) {
	t.Run("SetManager", func(t *testing.T) {
		inst := NewManager()
		_, err := SetManager(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetManager", func(t *testing.T) {
		inst := NewManager()
		ctx, err := SetManager(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetManager(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetManager", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "Manager missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errx.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetManager(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetManager(context.Background(), NewManager())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetManager(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetManager", func(t *testing.T) {
		var zero Manager

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetManager(context.Background(), NewManager())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetManager(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetManager(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromManager", func(t *testing.T) {
		rtype := reflect.TypeOf(NewManager())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewManager()

			ctx, err := SetManager(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromManager(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromManager(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithManager", func(t *testing.T) {
		rtype := reflect.TypeOf(NewManager())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewManager()

			ctx, err := SetManager(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithManager(ctx, func(obj Manager) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithManager(context.Background(), func(obj Manager) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
