// Code generated by MockGen. DO NOT EDIT.
// Source: ./envelope/interface.go
//
// Generated by this command:
//
//	mockgen -package=envelope -source=./envelope/interface.go -destination=mocks/envelope/interface_mock.go
//

// Package envelope is a generated GoMock package.
package envelope

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEnvelope is a mock of Envelope interface.
type MockEnvelope struct {
	ctrl     *gomock.Controller
	recorder *MockEnvelopeMockRecorder
	isgomock struct{}
}

// MockEnvelopeMockRecorder is the mock recorder for MockEnvelope.
type MockEnvelopeMockRecorder struct {
	mock *MockEnvelope
}

// NewMockEnvelope creates a new mock instance.
func NewMockEnvelope(ctrl *gomock.Controller) *MockEnvelope {
	mock := &MockEnvelope{ctrl: ctrl}
	mock.recorder = &MockEnvelopeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEnvelope) EXPECT() *MockEnvelopeMockRecorder {
	return m.recorder
}

// Body mocks base method.
func (m *MockEnvelope) Body() any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Body")
	ret0, _ := ret[0].(any)
	return ret0
}

// Body indicates an expected call of Body.
func (mr *MockEnvelopeMockRecorder) Body() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Body", reflect.TypeOf((*MockEnvelope)(nil).Body))
}

// Headers mocks base method.
func (m *MockEnvelope) Headers() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Headers")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// Headers indicates an expected call of Headers.
func (mr *MockEnvelopeMockRecorder) Headers() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Headers", reflect.TypeOf((*MockEnvelope)(nil).Headers))
}

// Status mocks base method.
func (m *MockEnvelope) Status() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Status")
	ret0, _ := ret[0].(int)
	return ret0
}

// Status indicates an expected call of Status.
func (mr *MockEnvelopeMockRecorder) Status() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Status", reflect.TypeOf((*MockEnvelope)(nil).Status))
}
