// Code generated by digen; DO NOT EDIT.

package timedcache

import (
	"context"
	"fmt"
	"reflect"
	"strings"
	"testing"
)

// --- TimedCache ---

func TestTimedCacheDI(t *testing.T) {
	t.Run("SetTimedCache", func(t *testing.T) {
		inst := NewDefault()
		_, err := SetTimedCache(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}
	})

	t.Run("GetTimedCache", func(t *testing.T) {
		inst := NewDefault()
		ctx, err := SetTimedCache(context.Background(), inst)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		res, err := GetTimedCache(ctx)
		if err != nil {
			t.Fatalf("Unexpected error: %#v", err)
		}

		if res != inst {
			t.Errorf("Unexpected result: %#v ", res)
		}
	})

	t.Run("MustGetTimedCache", func(t *testing.T) {
		t.Run("Panic when missing", func(t *testing.T) {
			ctx := context.Background()
			panicMsg := "TimedCache missing in context"

			defer func() {
				if r := recover(); r == nil {
					t.Fatalf("expected panic, got none")
				} else {
					// Panic value is an error from
					// errx.WithMessage; check the text.
					msg := fmt.Sprint(r)
					if !strings.Contains(msg, panicMsg) {
						t.Fatalf("panic = %q, want %q",
							msg,
							panicMsg)
					}
				}
			}()

			_ = MustGetTimedCache(ctx) // should panic
		})

		t.Run("No panic when present", func(t *testing.T) {
			ctx, err := SetTimedCache(context.Background(), NewDefault())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			defer func() {
				if r := recover(); r != nil {
					t.Fatalf("Unexpected panic: %v", r)
				}
			}()

			got := MustGetTimedCache(ctx)
			if got == nil {
				t.Fatal("Got nil instance")
			}
		})
	})

	t.Run("TryGetTimedCache", func(t *testing.T) {
		var zero TimedCache

		t.Run("Returns valid when present", func(t *testing.T) {
			ctx, err := SetTimedCache(context.Background(), NewDefault())
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val, ok := TryGetTimedCache(ctx)

			if !ok {
				t.Error("Expected true")
			}

			if val == zero {
				t.Errorf("Expected value")
			}
		})

		t.Run("Returns zero when not present", func(t *testing.T) {
			val, ok := TryGetTimedCache(context.Background())

			if ok {
				t.Error("Expected false")
			}

			if val != zero {
				t.Errorf("Expected zero got %#v", val)
			}
		})
	})

	t.Run("FromTimedCache", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefault())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefault()

			ctx, err := SetTimedCache(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			val := FromTimedCache(ctx)
			if val != inst {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			val := FromTimedCache(context.Background())

			if reflect.TypeOf(val) != rtype {
				t.Fatalf("Unexpected value: %#v", val)
			}
		})
	})

	t.Run("WithTimedCache", func(t *testing.T) {
		rtype := reflect.TypeOf(NewDefault())

		t.Run("Returns instance when present", func(t *testing.T) {
			inst := NewDefault()

			ctx, err := SetTimedCache(context.Background(), inst)
			if err != nil {
				t.Fatalf("Unexpected error: %v", err)
			}

			WithTimedCache(ctx, func(obj TimedCache) {
				if obj != inst {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})

		t.Run("Returns fallback when not present", func(t *testing.T) {
			WithTimedCache(context.Background(), func(obj TimedCache) {
				if reflect.TypeOf(obj) != rtype {
					t.Fatalf("Unexpected value: %#v", obj)
				}
			})
		})
	})
}
